/pointcloud_filter:
  ros__parameters:
    pointcloud_topic: "/ouster/points"
    filtered_pc_topic: "/ouster/points_filtered"
    laser_scan_topic: "/scan"
    min_x: -1.4
    max_x: 0.25
    min_y: -0.25
    max_y: 1.2
    min_z: -1.0
    max_z: 1.0
    filter_rings: false
    filter_box: true
    obtain_outside_box: true
    publish_filtered_pointcloud: true
    publish_laserscan: true
    scan_angle_min: -3.141592653589793
    scan_angle_max: 3.141592653589793
    scan_angle_increment: 0.006143
    scan_range_min: 0.3
    scan_range_max: 75.0
    laserscan_frame: ""